apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xho4bk3lj-java-quarkus
  janus-idp.io/tekton: xho4bk3lj-java-quarkus
  backstage.io/kubernetes-id: xho4bk3lj-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xho4bk3lj-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
